stages:
  data_ingestion:
    cmd: python src/mlflow_e2e/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlflow_e2e/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data

  prepare_base_model:
    cmd: python src/mlflow_e2e/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/mlflow_e2e/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/prepare_base_model/base_model.h5
      - artifacts/prepare_base_model/base_model_updated.h5

  training:
    cmd: python src/mlflow_e2e/pipeline/stage_03_model_trainer.py
    deps:
      - src/mlflow_e2e/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/prepare_base_model/base_model_updated.h5
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/mlflow_e2e/pipeline/stage_04_model_evaluation.py
    deps:
      - src/mlflow_e2e/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - params.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/training/model.h5
    metrics:
      - scores.json:
          cache: false
